# Generated by Django 4.0 on 2022-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.IntegerField(default='0'),
        ),
    ]
