# Generated by Django 4.0.2 on 2022-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_age_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
